### ISSUE TITLE
Source servers don't work over default bridge network with port config

### ISSUE THREAD

**Issue by matthewh86** [GameServerManagers/LinuxGSM-Docker#3]
- No additional configuration from defaults provided.
- linuxgsm:latest is a locally created docker image with jq dependency included
  - https://github.com/GameServerManagers/LinuxGSM-Docker/pull/2
- Using the following docker-compose.yml

```
version: '2'

services:
  linuxgsm-css:
    image: linuxgsm:latest
    container_name: linuxgsm-css
    ports:
      - "27015:27015"
    volumes:
      - linuxgsm_css_vol:/home/lgsm
    restart: unless-stopped

volumes:
  linuxgsm_css_vol:
    driver_opts:
      type: none
      device: /srv/quickload/docker-volumes/linuxgsm/css-server
      o: bind
```

Commands run on the container:
```
./linuxgsm cssserver
./cssserver ai
```

./cssserver m output
```
lgsm@c3fd5fa96cc6:~$ ./cssserver m
[ INFO ] Monitor cssserver: Check IP: 172.21.0.3
[  OK  ] Monitor cssserver: Checking session: OK
[  OK  ] Monitor cssserver: Querying port: gsquery: 172.21.0.3:27015 : 0/1: OK
```
