### ISSUE TITLE
Source server LAN discovery doesn't work over macvlan network configuration

### ISSUE THREAD

**Issue by matthewh86** [GameServerManagers/LinuxGSM-Docker#4]
- Additional configuration:
  - as per https://github.com/GameServerManagers/LinuxGSM/wiki/LAN-Discovery
  - /lgsm/config-lgsm/cssserver/cssserver.cfg
```
ip="192.168.1.150
maxplayers="24"

fn_parms(){
parms="-game cstrike -strictportbind -ip 0.0.0.0 -port ${port} +sv_setsteamaccount ${gslt} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers ${maxplayers} +sv_lan 1 -nohltv"
}
```
- linuxgsm:latest is a locally created docker image with jq dependency included
  - #2
- Using the following docker-compose.yml

```
version: '2'

services:
  linuxgsm-css:
    image: linuxgsm:latest
    container_name: linuxgsm-css
    networks:
      enp1s0f0_vlan:
        ipv4_address: 192.168.1.150
    volumes:
      - linuxgsm_css_vol:/home/lgsm
    restart: unless-stopped

networks:
  enp1s0f0_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0f0
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  linuxgsm_css_vol:
    driver_opts:
      type: none
      device: /srv/quickload/docker-volumes/linuxgsm/css-server
      o: bind
```
